/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import { relations } from "@payloadcms/db-postgres/drizzle";
import {
  boolean,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  serial,
  timestamp,
  uniqueIndex,
  varchar,
} from "@payloadcms/db-postgres/drizzle/pg-core";

export const enum_resumes_status = pgEnum("enum_resumes_status", ["draft", "published"]);
export const enum__resumes_v_version_status = pgEnum("enum__resumes_v_version_status", [
  "draft",
  "published",
]);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    caption: varchar("caption"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const resumes_experience = pgTable(
  "resumes_experience",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    jobTitle: varchar("job_title"),
    company: varchar("company"),
    description: jsonb("description"),
    startDate: timestamp("start_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    current: boolean("current"),
    endDate: timestamp("end_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("resumes_experience_order_idx").on(columns._order),
    index("resumes_experience_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [resumes.id],
      name: "resumes_experience_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const resumes = pgTable(
  "resumes",
  {
    id: serial("id").primaryKey(),
    user: integer("user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    description: varchar("description"),
    skills: jsonb("skills"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_resumes_status("_status").default("draft"),
  },
  (columns) => [
    index("resumes_user_idx").on(columns.user),
    index("resumes_updated_at_idx").on(columns.updatedAt),
    index("resumes_created_at_idx").on(columns.createdAt),
    index("resumes__status_idx").on(columns._status),
  ],
);

export const _resumes_v_version_experience = pgTable(
  "_resumes_v_version_experience",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    jobTitle: varchar("job_title"),
    company: varchar("company"),
    description: jsonb("description"),
    startDate: timestamp("start_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    current: boolean("current"),
    endDate: timestamp("end_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_resumes_v_version_experience_order_idx").on(columns._order),
    index("_resumes_v_version_experience_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_resumes_v.id],
      name: "_resumes_v_version_experience_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _resumes_v = pgTable(
  "_resumes_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => resumes.id, {
      onDelete: "set null",
    }),
    version_user: integer("version_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    version_description: varchar("version_description"),
    version_skills: jsonb("version_skills"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__resumes_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_resumes_v_parent_idx").on(columns.parent),
    index("_resumes_v_version_version_user_idx").on(columns.version_user),
    index("_resumes_v_version_version_updated_at_idx").on(columns.version_updatedAt),
    index("_resumes_v_version_version_created_at_idx").on(columns.version_createdAt),
    index("_resumes_v_version_version__status_idx").on(columns.version__status),
    index("_resumes_v_created_at_idx").on(columns.createdAt),
    index("_resumes_v_updated_at_idx").on(columns.updatedAt),
    index("_resumes_v_latest_idx").on(columns.latest),
  ],
);

export const applicants = pgTable(
  "applicants",
  {
    id: serial("id").primaryKey(),
    name_firstName: varchar("name_first_name"),
    name_lastName: varchar("name_last_name"),
    address_street: varchar("address_street"),
    address_city: varchar("address_city"),
    address_state: varchar("address_state"),
    address_postalCode: varchar("address_postal_code"),
    address_country: varchar("address_country"),
    phone: varchar("phone"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("applicants_updated_at_idx").on(columns.updatedAt),
    index("applicants_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    resumesID: integer("resumes_id"),
    applicantsID: integer("applicants_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_resumes_id_idx").on(columns.resumesID),
    index("payload_locked_documents_rels_applicants_id_idx").on(columns.applicantsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["resumesID"]],
      foreignColumns: [resumes.id],
      name: "payload_locked_documents_rels_resumes_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["applicantsID"]],
      foreignColumns: [applicants.id],
      name: "payload_locked_documents_rels_applicants_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: "sessions",
  }),
}));
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_resumes_experience = relations(resumes_experience, ({ one }) => ({
  _parentID: one(resumes, {
    fields: [resumes_experience._parentID],
    references: [resumes.id],
    relationName: "experience",
  }),
}));
export const relations_resumes = relations(resumes, ({ one, many }) => ({
  user: one(users, {
    fields: [resumes.user],
    references: [users.id],
    relationName: "user",
  }),
  experience: many(resumes_experience, {
    relationName: "experience",
  }),
}));
export const relations__resumes_v_version_experience = relations(
  _resumes_v_version_experience,
  ({ one }) => ({
    _parentID: one(_resumes_v, {
      fields: [_resumes_v_version_experience._parentID],
      references: [_resumes_v.id],
      relationName: "version_experience",
    }),
  }),
);
export const relations__resumes_v = relations(_resumes_v, ({ one, many }) => ({
  parent: one(resumes, {
    fields: [_resumes_v.parent],
    references: [resumes.id],
    relationName: "parent",
  }),
  version_user: one(users, {
    fields: [_resumes_v.version_user],
    references: [users.id],
    relationName: "version_user",
  }),
  version_experience: many(_resumes_v_version_experience, {
    relationName: "version_experience",
  }),
}));
export const relations_applicants = relations(applicants, () => ({}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    resumesID: one(resumes, {
      fields: [payload_locked_documents_rels.resumesID],
      references: [resumes.id],
      relationName: "resumes",
    }),
    applicantsID: one(applicants, {
      fields: [payload_locked_documents_rels.applicantsID],
      references: [applicants.id],
      relationName: "applicants",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: "_rels",
  }),
}));
export const relations_payload_migrations = relations(payload_migrations, () => ({}));

type DatabaseSchema = {
  enum_resumes_status: typeof enum_resumes_status;
  enum__resumes_v_version_status: typeof enum__resumes_v_version_status;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  resumes_experience: typeof resumes_experience;
  resumes: typeof resumes;
  _resumes_v_version_experience: typeof _resumes_v_version_experience;
  _resumes_v: typeof _resumes_v;
  applicants: typeof applicants;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_resumes_experience: typeof relations_resumes_experience;
  relations_resumes: typeof relations_resumes;
  relations__resumes_v_version_experience: typeof relations__resumes_v_version_experience;
  relations__resumes_v: typeof relations__resumes_v;
  relations_applicants: typeof relations_applicants;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
