/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  serial,
  timestamp,
  jsonb,
  boolean,
  numeric,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_resumes_status = pgEnum("enum_resumes_status", [
  "draft",
  "published",
]);
export const enum__resumes_v_version_status = pgEnum(
  "enum__resumes_v_version_status",
  ["draft", "published"],
);
export const enum_references_contact_methods_type = pgEnum(
  "enum_references_contact_methods_type",
  ["phone", "email"],
);
export const enum_job_applications_status = pgEnum(
  "enum_job_applications_status",
  ["draft", "published"],
);
export const enum__job_applications_v_version_status = pgEnum(
  "enum__job_applications_v_version_status",
  ["draft", "published"],
);

export const applicants_social_links = pgTable(
  "applicants_social_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    label: varchar("label").notNull(),
    url: varchar("url").notNull(),
  },
  (columns) => [
    index("applicants_social_links_order_idx").on(columns._order),
    index("applicants_social_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [applicants.id],
      name: "applicants_social_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const applicants = pgTable(
  "applicants",
  {
    id: serial("id").primaryKey(),
    fullName: varchar("full_name"),
    firstName: varchar("first_name").notNull(),
    lastName: varchar("last_name").notNull(),
    location_street: varchar("location_street"),
    location_city: varchar("location_city"),
    location_state: varchar("location_state"),
    location_postalCode: varchar("location_postal_code"),
    location_country: varchar("location_country"),
    phone: varchar("phone"),
    email: varchar("email").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("applicants_updated_at_idx").on(columns.updatedAt),
    index("applicants_created_at_idx").on(columns.createdAt),
  ],
);

export const resumes_skill_sections = pgTable(
  "resumes_skill_sections",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    category: varchar("category"),
  },
  (columns) => [
    index("resumes_skill_sections_order_idx").on(columns._order),
    index("resumes_skill_sections_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [resumes.id],
      name: "resumes_skill_sections_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const resumes_experience = pgTable(
  "resumes_experience",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    jobTitle: varchar("job_title"),
    company: varchar("company"),
    description: jsonb("description"),
    startDate: timestamp("start_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    current: boolean("current"),
    endDate: timestamp("end_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    location_street: varchar("location_street"),
    location_city: varchar("location_city"),
    location_state: varchar("location_state"),
    location_postalCode: varchar("location_postal_code"),
    location_country: varchar("location_country"),
  },
  (columns) => [
    index("resumes_experience_order_idx").on(columns._order),
    index("resumes_experience_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [resumes.id],
      name: "resumes_experience_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const resumes_education = pgTable(
  "resumes_education",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    school: varchar("school"),
    degree: varchar("degree"),
    startDate: timestamp("start_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    endDate: timestamp("end_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("resumes_education_order_idx").on(columns._order),
    index("resumes_education_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [resumes.id],
      name: "resumes_education_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const resumes = pgTable(
  "resumes",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    applicant: integer("applicant_id").references(() => applicants.id, {
      onDelete: "set null",
    }),
    description: varchar("description"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_resumes_status("_status").default("draft"),
  },
  (columns) => [
    index("resumes_applicant_idx").on(columns.applicant),
    index("resumes_updated_at_idx").on(columns.updatedAt),
    index("resumes_created_at_idx").on(columns.createdAt),
    index("resumes__status_idx").on(columns._status),
  ],
);

export const resumes_texts = pgTable(
  "resumes_texts",
  {
    id: serial("id").primaryKey(),
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    text: varchar("text"),
  },
  (columns) => [
    index("resumes_texts_order_parent").on(columns.order, columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [resumes.id],
      name: "resumes_texts_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const resumes_rels = pgTable(
  "resumes_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    referencesID: integer("references_id"),
  },
  (columns) => [
    index("resumes_rels_order_idx").on(columns.order),
    index("resumes_rels_parent_idx").on(columns.parent),
    index("resumes_rels_path_idx").on(columns.path),
    index("resumes_rels_references_id_idx").on(columns.referencesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [resumes.id],
      name: "resumes_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["referencesID"]],
      foreignColumns: [references.id],
      name: "resumes_rels_references_fk",
    }).onDelete("cascade"),
  ],
);

export const _resumes_v_version_skill_sections = pgTable(
  "_resumes_v_version_skill_sections",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    category: varchar("category"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_resumes_v_version_skill_sections_order_idx").on(columns._order),
    index("_resumes_v_version_skill_sections_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_resumes_v.id],
      name: "_resumes_v_version_skill_sections_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _resumes_v_version_experience = pgTable(
  "_resumes_v_version_experience",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    jobTitle: varchar("job_title"),
    company: varchar("company"),
    description: jsonb("description"),
    startDate: timestamp("start_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    current: boolean("current"),
    endDate: timestamp("end_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    location_street: varchar("location_street"),
    location_city: varchar("location_city"),
    location_state: varchar("location_state"),
    location_postalCode: varchar("location_postal_code"),
    location_country: varchar("location_country"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_resumes_v_version_experience_order_idx").on(columns._order),
    index("_resumes_v_version_experience_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_resumes_v.id],
      name: "_resumes_v_version_experience_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _resumes_v_version_education = pgTable(
  "_resumes_v_version_education",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    school: varchar("school"),
    degree: varchar("degree"),
    startDate: timestamp("start_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    endDate: timestamp("end_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_resumes_v_version_education_order_idx").on(columns._order),
    index("_resumes_v_version_education_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_resumes_v.id],
      name: "_resumes_v_version_education_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _resumes_v = pgTable(
  "_resumes_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => resumes.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_applicant: integer("version_applicant_id").references(
      () => applicants.id,
      {
        onDelete: "set null",
      },
    ),
    version_description: varchar("version_description"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__resumes_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_resumes_v_parent_idx").on(columns.parent),
    index("_resumes_v_version_version_applicant_idx").on(
      columns.version_applicant,
    ),
    index("_resumes_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_resumes_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_resumes_v_version_version__status_idx").on(columns.version__status),
    index("_resumes_v_created_at_idx").on(columns.createdAt),
    index("_resumes_v_updated_at_idx").on(columns.updatedAt),
    index("_resumes_v_latest_idx").on(columns.latest),
  ],
);

export const _resumes_v_texts = pgTable(
  "_resumes_v_texts",
  {
    id: serial("id").primaryKey(),
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    text: varchar("text"),
  },
  (columns) => [
    index("_resumes_v_texts_order_parent").on(columns.order, columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_resumes_v.id],
      name: "_resumes_v_texts_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const _resumes_v_rels = pgTable(
  "_resumes_v_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    referencesID: integer("references_id"),
  },
  (columns) => [
    index("_resumes_v_rels_order_idx").on(columns.order),
    index("_resumes_v_rels_parent_idx").on(columns.parent),
    index("_resumes_v_rels_path_idx").on(columns.path),
    index("_resumes_v_rels_references_id_idx").on(columns.referencesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_resumes_v.id],
      name: "_resumes_v_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["referencesID"]],
      foreignColumns: [references.id],
      name: "_resumes_v_rels_references_fk",
    }).onDelete("cascade"),
  ],
);

export const references_contact_methods = pgTable(
  "references_contact_methods",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    type: enum_references_contact_methods_type("type"),
    email: varchar("email"),
    phone: varchar("phone"),
  },
  (columns) => [
    index("references_contact_methods_order_idx").on(columns._order),
    index("references_contact_methods_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [references.id],
      name: "references_contact_methods_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const references = pgTable(
  "references",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    company: varchar("company"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("references_updated_at_idx").on(columns.updatedAt),
    index("references_created_at_idx").on(columns.createdAt),
  ],
);

export const job_applications = pgTable(
  "job_applications",
  {
    id: serial("id").primaryKey(),
    jobPostingUrl: varchar("job_posting_url"),
    jobTitle: varchar("job_title"),
    company: varchar("company"),
    location_street: varchar("location_street"),
    location_city: varchar("location_city"),
    location_state: varchar("location_state"),
    location_postalCode: varchar("location_postal_code"),
    location_country: varchar("location_country"),
    applicant: integer("applicant_id").references(() => applicants.id, {
      onDelete: "set null",
    }),
    resume: integer("resume_id").references(() => resumes.id, {
      onDelete: "set null",
    }),
    coverLetter: jsonb("cover_letter"),
    submittedAt: timestamp("submitted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_job_applications_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("job_applications_job_posting_url_idx").on(
      columns.jobPostingUrl,
    ),
    index("job_applications_company_idx").on(columns.company),
    index("job_applications_applicant_idx").on(columns.applicant),
    index("job_applications_resume_idx").on(columns.resume),
    index("job_applications_updated_at_idx").on(columns.updatedAt),
    index("job_applications_created_at_idx").on(columns.createdAt),
    index("job_applications__status_idx").on(columns._status),
  ],
);

export const _job_applications_v = pgTable(
  "_job_applications_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => job_applications.id, {
      onDelete: "set null",
    }),
    version_jobPostingUrl: varchar("version_job_posting_url"),
    version_jobTitle: varchar("version_job_title"),
    version_company: varchar("version_company"),
    version_location_street: varchar("version_location_street"),
    version_location_city: varchar("version_location_city"),
    version_location_state: varchar("version_location_state"),
    version_location_postalCode: varchar("version_location_postal_code"),
    version_location_country: varchar("version_location_country"),
    version_applicant: integer("version_applicant_id").references(
      () => applicants.id,
      {
        onDelete: "set null",
      },
    ),
    version_resume: integer("version_resume_id").references(() => resumes.id, {
      onDelete: "set null",
    }),
    version_coverLetter: jsonb("version_cover_letter"),
    version_submittedAt: timestamp("version_submitted_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__job_applications_v_version_status("version__status").default(
        "draft",
      ),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_job_applications_v_parent_idx").on(columns.parent),
    index("_job_applications_v_version_version_job_posting_url_idx").on(
      columns.version_jobPostingUrl,
    ),
    index("_job_applications_v_version_version_company_idx").on(
      columns.version_company,
    ),
    index("_job_applications_v_version_version_applicant_idx").on(
      columns.version_applicant,
    ),
    index("_job_applications_v_version_version_resume_idx").on(
      columns.version_resume,
    ),
    index("_job_applications_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_job_applications_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_job_applications_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_job_applications_v_created_at_idx").on(columns.createdAt),
    index("_job_applications_v_updated_at_idx").on(columns.updatedAt),
    index("_job_applications_v_latest_idx").on(columns.latest),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    caption: varchar("caption"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    applicantsID: integer("applicants_id"),
    resumesID: integer("resumes_id"),
    referencesID: integer("references_id"),
    "job-applicationsID": integer("job_applications_id"),
    mediaID: integer("media_id"),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_applicants_id_idx").on(
      columns.applicantsID,
    ),
    index("payload_locked_documents_rels_resumes_id_idx").on(columns.resumesID),
    index("payload_locked_documents_rels_references_id_idx").on(
      columns.referencesID,
    ),
    index("payload_locked_documents_rels_job_applications_id_idx").on(
      columns["job-applicationsID"],
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["applicantsID"]],
      foreignColumns: [applicants.id],
      name: "payload_locked_documents_rels_applicants_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["resumesID"]],
      foreignColumns: [resumes.id],
      name: "payload_locked_documents_rels_resumes_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["referencesID"]],
      foreignColumns: [references.id],
      name: "payload_locked_documents_rels_references_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["job-applicationsID"]],
      foreignColumns: [job_applications.id],
      name: "payload_locked_documents_rels_job_applications_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_applicants_social_links = relations(
  applicants_social_links,
  ({ one }) => ({
    _parentID: one(applicants, {
      fields: [applicants_social_links._parentID],
      references: [applicants.id],
      relationName: "socialLinks",
    }),
  }),
);
export const relations_applicants = relations(applicants, ({ many }) => ({
  socialLinks: many(applicants_social_links, {
    relationName: "socialLinks",
  }),
}));
export const relations_resumes_skill_sections = relations(
  resumes_skill_sections,
  ({ one }) => ({
    _parentID: one(resumes, {
      fields: [resumes_skill_sections._parentID],
      references: [resumes.id],
      relationName: "skillSections",
    }),
  }),
);
export const relations_resumes_experience = relations(
  resumes_experience,
  ({ one }) => ({
    _parentID: one(resumes, {
      fields: [resumes_experience._parentID],
      references: [resumes.id],
      relationName: "experience",
    }),
  }),
);
export const relations_resumes_education = relations(
  resumes_education,
  ({ one }) => ({
    _parentID: one(resumes, {
      fields: [resumes_education._parentID],
      references: [resumes.id],
      relationName: "education",
    }),
  }),
);
export const relations_resumes_texts = relations(resumes_texts, ({ one }) => ({
  parent: one(resumes, {
    fields: [resumes_texts.parent],
    references: [resumes.id],
    relationName: "_texts",
  }),
}));
export const relations_resumes_rels = relations(resumes_rels, ({ one }) => ({
  parent: one(resumes, {
    fields: [resumes_rels.parent],
    references: [resumes.id],
    relationName: "_rels",
  }),
  referencesID: one(references, {
    fields: [resumes_rels.referencesID],
    references: [references.id],
    relationName: "references",
  }),
}));
export const relations_resumes = relations(resumes, ({ one, many }) => ({
  applicant: one(applicants, {
    fields: [resumes.applicant],
    references: [applicants.id],
    relationName: "applicant",
  }),
  skillSections: many(resumes_skill_sections, {
    relationName: "skillSections",
  }),
  experience: many(resumes_experience, {
    relationName: "experience",
  }),
  education: many(resumes_education, {
    relationName: "education",
  }),
  _texts: many(resumes_texts, {
    relationName: "_texts",
  }),
  _rels: many(resumes_rels, {
    relationName: "_rels",
  }),
}));
export const relations__resumes_v_version_skill_sections = relations(
  _resumes_v_version_skill_sections,
  ({ one }) => ({
    _parentID: one(_resumes_v, {
      fields: [_resumes_v_version_skill_sections._parentID],
      references: [_resumes_v.id],
      relationName: "version_skillSections",
    }),
  }),
);
export const relations__resumes_v_version_experience = relations(
  _resumes_v_version_experience,
  ({ one }) => ({
    _parentID: one(_resumes_v, {
      fields: [_resumes_v_version_experience._parentID],
      references: [_resumes_v.id],
      relationName: "version_experience",
    }),
  }),
);
export const relations__resumes_v_version_education = relations(
  _resumes_v_version_education,
  ({ one }) => ({
    _parentID: one(_resumes_v, {
      fields: [_resumes_v_version_education._parentID],
      references: [_resumes_v.id],
      relationName: "version_education",
    }),
  }),
);
export const relations__resumes_v_texts = relations(
  _resumes_v_texts,
  ({ one }) => ({
    parent: one(_resumes_v, {
      fields: [_resumes_v_texts.parent],
      references: [_resumes_v.id],
      relationName: "_texts",
    }),
  }),
);
export const relations__resumes_v_rels = relations(
  _resumes_v_rels,
  ({ one }) => ({
    parent: one(_resumes_v, {
      fields: [_resumes_v_rels.parent],
      references: [_resumes_v.id],
      relationName: "_rels",
    }),
    referencesID: one(references, {
      fields: [_resumes_v_rels.referencesID],
      references: [references.id],
      relationName: "references",
    }),
  }),
);
export const relations__resumes_v = relations(_resumes_v, ({ one, many }) => ({
  parent: one(resumes, {
    fields: [_resumes_v.parent],
    references: [resumes.id],
    relationName: "parent",
  }),
  version_applicant: one(applicants, {
    fields: [_resumes_v.version_applicant],
    references: [applicants.id],
    relationName: "version_applicant",
  }),
  version_skillSections: many(_resumes_v_version_skill_sections, {
    relationName: "version_skillSections",
  }),
  version_experience: many(_resumes_v_version_experience, {
    relationName: "version_experience",
  }),
  version_education: many(_resumes_v_version_education, {
    relationName: "version_education",
  }),
  _texts: many(_resumes_v_texts, {
    relationName: "_texts",
  }),
  _rels: many(_resumes_v_rels, {
    relationName: "_rels",
  }),
}));
export const relations_references_contact_methods = relations(
  references_contact_methods,
  ({ one }) => ({
    _parentID: one(references, {
      fields: [references_contact_methods._parentID],
      references: [references.id],
      relationName: "contactMethods",
    }),
  }),
);
export const relations_references = relations(references, ({ many }) => ({
  contactMethods: many(references_contact_methods, {
    relationName: "contactMethods",
  }),
}));
export const relations_job_applications = relations(
  job_applications,
  ({ one }) => ({
    applicant: one(applicants, {
      fields: [job_applications.applicant],
      references: [applicants.id],
      relationName: "applicant",
    }),
    resume: one(resumes, {
      fields: [job_applications.resume],
      references: [resumes.id],
      relationName: "resume",
    }),
  }),
);
export const relations__job_applications_v = relations(
  _job_applications_v,
  ({ one }) => ({
    parent: one(job_applications, {
      fields: [_job_applications_v.parent],
      references: [job_applications.id],
      relationName: "parent",
    }),
    version_applicant: one(applicants, {
      fields: [_job_applications_v.version_applicant],
      references: [applicants.id],
      relationName: "version_applicant",
    }),
    version_resume: one(resumes, {
      fields: [_job_applications_v.version_resume],
      references: [resumes.id],
      relationName: "version_resume",
    }),
  }),
);
export const relations_media = relations(media, () => ({}));
export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    applicantsID: one(applicants, {
      fields: [payload_locked_documents_rels.applicantsID],
      references: [applicants.id],
      relationName: "applicants",
    }),
    resumesID: one(resumes, {
      fields: [payload_locked_documents_rels.resumesID],
      references: [resumes.id],
      relationName: "resumes",
    }),
    referencesID: one(references, {
      fields: [payload_locked_documents_rels.referencesID],
      references: [references.id],
      relationName: "references",
    }),
    "job-applicationsID": one(job_applications, {
      fields: [payload_locked_documents_rels["job-applicationsID"]],
      references: [job_applications.id],
      relationName: "job-applications",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_resumes_status: typeof enum_resumes_status;
  enum__resumes_v_version_status: typeof enum__resumes_v_version_status;
  enum_references_contact_methods_type: typeof enum_references_contact_methods_type;
  enum_job_applications_status: typeof enum_job_applications_status;
  enum__job_applications_v_version_status: typeof enum__job_applications_v_version_status;
  applicants_social_links: typeof applicants_social_links;
  applicants: typeof applicants;
  resumes_skill_sections: typeof resumes_skill_sections;
  resumes_experience: typeof resumes_experience;
  resumes_education: typeof resumes_education;
  resumes: typeof resumes;
  resumes_texts: typeof resumes_texts;
  resumes_rels: typeof resumes_rels;
  _resumes_v_version_skill_sections: typeof _resumes_v_version_skill_sections;
  _resumes_v_version_experience: typeof _resumes_v_version_experience;
  _resumes_v_version_education: typeof _resumes_v_version_education;
  _resumes_v: typeof _resumes_v;
  _resumes_v_texts: typeof _resumes_v_texts;
  _resumes_v_rels: typeof _resumes_v_rels;
  references_contact_methods: typeof references_contact_methods;
  references: typeof references;
  job_applications: typeof job_applications;
  _job_applications_v: typeof _job_applications_v;
  media: typeof media;
  users_sessions: typeof users_sessions;
  users: typeof users;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_applicants_social_links: typeof relations_applicants_social_links;
  relations_applicants: typeof relations_applicants;
  relations_resumes_skill_sections: typeof relations_resumes_skill_sections;
  relations_resumes_experience: typeof relations_resumes_experience;
  relations_resumes_education: typeof relations_resumes_education;
  relations_resumes_texts: typeof relations_resumes_texts;
  relations_resumes_rels: typeof relations_resumes_rels;
  relations_resumes: typeof relations_resumes;
  relations__resumes_v_version_skill_sections: typeof relations__resumes_v_version_skill_sections;
  relations__resumes_v_version_experience: typeof relations__resumes_v_version_experience;
  relations__resumes_v_version_education: typeof relations__resumes_v_version_education;
  relations__resumes_v_texts: typeof relations__resumes_v_texts;
  relations__resumes_v_rels: typeof relations__resumes_v_rels;
  relations__resumes_v: typeof relations__resumes_v;
  relations_references_contact_methods: typeof relations_references_contact_methods;
  relations_references: typeof relations_references;
  relations_job_applications: typeof relations_job_applications;
  relations__job_applications_v: typeof relations__job_applications_v;
  relations_media: typeof relations_media;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
