name: CI

on:
  pull_request:
    branches:
      - main
      - master
permissions:
  contents: read

env:
  PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Lint
        run: moon run :lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Build
        run: moon run :build

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-noble
      options: --user 1001
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Test
        run: moon run :test
